#WORDPRESS REPLICATIONCONTROLLER.YML
 
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress-rc
spec:
 replicas: 3
 selector:
    app: wordpress
 template:
   metadata:
      labels: 
        app: wordpress
   spec:
     containers:
     - name: wordpress
       image: 2307297/wordpress-mysql
       ports:
       - containerPort: 80
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#WORDPRESS SERVICE.YML

apiVersion: v1
kind: Service
metadata:
   name: wordpress-svc
   labels:
      app: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: wordpress
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------



#MYSQL SERVICE.YML

apiVersion: v1
kind: Service
metadata:
      name: mariadb-svc
      labels:
        app: mariadb:10.3
spec:
   type: ClusterIP
   ports:
    - port: 3306
   selector:
       app: mariadb:10.3
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#MYSQL REPLICATIONCONTROLLER.YML


apiVersion: v1
kind: ReplicationController
metadata:
   name: mariadb-rc
spec:
  replicas: 1
  selector:
    labels:
      app: mariadb:10.3
   template:
     metadata:
        labels:
         app: mariadb:10.3
      spec:
        containers:
         -  name: mariadb:10.3
            image:
            ports:
            - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "wordpress"
